### ISSUE TITLE
[wordgame] Suggest a word

### ISSUE THREAD

**Issue by bazz1tv** [bazzinotti/ayumi#16]
allows users to suggest a word to be added to the dictionary

**Comment by bazz1tv** [comment]
implemented by https://github.com/bazzinotti/ayumi/tree/ae451ab64ecab501d396c3f685d3a90c1a14737d

but without multi-channel dicts ..

**Comment by bazzinotti** [comment]
check if '\n' is at EOF when appending an entry to dictfile.. otherwise we are appending directly to a pre-existing word!
