### ISSUE TITLE
[highscores] Sort by "first-come-first-serve"

### ISSUE THREAD

**Issue by bazz1tv** [bazzinotti/ayumi#45]
Redis ZScore sometimes "re-sorts" entries of the same score .. but they really should be first-come-first-serve order ... I will have to make my own "datatype" for this .

**Comment by bazzinotti** [comment]
Could make a new datatype that has two "things"
- time submitted
- score

**Comment by bazz1tv** [comment]
Add a new key-value thingy that has time

## Key

`wordgames:highscores:#{user}:time`

## Value

`Time.new.to_i`

# Ordering a Highscores listing
- Get the highscore ZSet
- Iterate through to collect usernames
  - Also, find conflicting highscores
- for conflicting highscores (create empty array)
  - (new loop)Grab the user:time / append to an array
  - Sort array (should be a hash to maintain connection to Nickname)

Unneeded notes that will be left for importance

## Hash values
- score
- time of change
